Use bash built-in 'getopts' in maker.
Misc corrections: better checking of arguments, some typos in the messages, better error codes.

diff --git a/maker b/maker
--- a/maker
+++ b/maker
@@ -14,6 +14,11 @@
 LOGFILE=rahd.log
 SBCL=
 
+# Differentiated error numbers make for easier bug hunting. Hopefully we won't
+# have to use them.
+E_MAKERERROR=83
+E_SCRIPTERROR=84
+
 #
 # The msg recursive function takes care of the pretty-printing.
 # It uses "fmt" to stick to 75 characters columns.
@@ -24,7 +29,7 @@ function msg()
     if [ $1 = "err" ]; then
       echo ""
       echo "! maker error: $2." | fmt >&2
-      exit 1
+      exit $E_MAKERERROR
     elif [ $1 = "inf" ]; then
       echo "* $2." | fmt
       return 0
@@ -33,7 +38,7 @@ function msg()
     if [ $1 = "ser" ]; then
       echo ""
       echo "! script error ($2): $3. Please file a bug." | fmt >&2
-      exit 1
+      exit $E_SCRIPTERROR
     fi
     msg "ser" "msg" "unexpected message type"
   else
@@ -43,50 +48,49 @@ function msg()
 
 
 #
-# The option parsing function. Uses getopt, a more full-featured command than
-# the getopts bash built-in function.
+# Macro function to print a usage message.
 #
-tmpopt=`getopt -o hn --long help,sbcl:,logfile:,noclean -n \`basename $0\` -- "$@"`
-# Check the getopt return code
-if [ $? != 0 ]; then 
-   msg "err" "option parse error"
-fi
-
-eval set -- "$tmpopt"
-
-#for arg do echo '--> '"\`$arg'" ; done
-while true ; do
-  case "$1" in
-    --sbcl) 
-        localsbcl=`(cd \`dirname $2\` && pwd) 2>/dev/null`/`basename $2 2>/dev/null`
-        if [ $? != 0 ]; then
-          msg "err" "SBCL binary not found at $2. Would you mind double-checking?"
-        fi
-        msg "inf" "SBCL binary set to '$localsbcl'"
-        shift 2;;
-    --logfile)
-        LOGFILE=`(cd \`dirname $2\` && pwd) 2>/dev/null`/`basename $2 2>/dev/null`
-        if [ $? != 0 ]; then
-          msg "err" "the log file path at $2 seems incorrect. Would you mind double-checking?"
-        fi
-        msg "inf" "Compilation output into '$LOGFILE'"
-        shift 2;;
-    -n|--noclean)
-        msg "inf" "Fasl files will be preserved"
-        keepfasl="yes"
-        shift;;
-    -h|--help) 
-        echo -e "Usage: `basename $0` [--sbcl=FILE] [--noclean] [--help]
+function print_usage()
+{
+  echo -e "Usage: `basename $0` [-c FILE] [-l FILE] [-n] [-h]
 Options:
-  --sbcl=FILE \t\t Specify the location of the SBCL executable.
-  --logfile=FILE\t Specify where to store the compilation verbiage.
-  -n, --noclean \t Don't remove fasl files before or after the compilation step.
-  -h, --help  \t\t Print this message and exit."
-        exit 0;;
-    --) shift; break;;
-    *) msg "ser" "option parsing" "unrecognized argument '$1'";;
+  -c FILE \t Provide the location of the SBCL compiler and toplevel.
+  -l FILE \t Specify where to store the compilation output.
+  -n  \t\t Don't remove fasl files before or after the compilation step.
+  -h  \t\t Print this message and exit."
+}
+
+
+#
+# The option parsing function. Uses getopts, a bash built-in function.
+#
+while getopts ":c:l:nh" opt
+do
+  case $opt in 
+    h   ) print_usage
+          exit 0;;
+    c   ) sbcldir=`(cd \`dirname $OPTARG\` && pwd) 2>/dev/null`
+          if [ $? != 0 ]; then
+            msg "err" "SBCL binary path $OPTARG seems incorrect. Can't access the containing directory"
+          fi
+          localsbcl=$sbcldir/`basename $OPTARG 2>/dev/null`
+          if [ ! -e $localsbcl ] || [ ! -x $localsbcl ]; then
+            msg "err" "SBCL binary at $OPTARG was not found, or does not have executable permission"
+          fi
+          msg "inf" "SBCL binary set to '$localsbcl'";;
+    l   ) logdir=`(cd \`dirname $OPTARG\` && pwd) 2>/dev/null`
+          if [ $? != 0 ] || [ ! -w $logdir ]; then
+            msg "err" "the log file path $OPTARG seems incorrect, or has incompatible permissions"
+          fi
+          LOGFILE=$logdir/`basename $OPTARG 2>/dev/null`
+          msg "inf" "Compilation output into '$LOGFILE'";;
+    n   ) msg "inf" "Fasl files will be preserved"
+          keepfasl="yes";;
+    *   ) msg "err" "unrecognized option '$OPTARG'. Type './maker -h' to list available options";;
   esac
 done
+
+shift $(($OPTIND - 1))
 
 
 #
@@ -111,7 +115,7 @@ msg "inf" "SBCL binary set to $SBCL"
 # Clear potential remaining binary files
 #
 if [ "$keepfasl" != "yes" ]; then
-  msg "inf" "Clearing stray fasl files"
+  msg "inf" "Removing stray fasl files"
   rm -f *.fasl
 fi
 
@@ -122,10 +126,10 @@ msg "inf" "Initiating RAHD compilation"
 echo -n "  Compiling... "
 ($SBCL < Makefile.sbcl) &> $LOGFILE
 if [ $? != 0 ]; then
-  msg "err" "compilation error. See file $LOGFILE for details"
+  msg "err" "compilation error. See $LOGFILE for details"
 else
   echo "done."
-  msg "inf" "Compilation succeded. Good to go"
+  msg "inf" "Compilation succeeded. See $LOGFILE for details"
 fi
 
 #
@@ -136,3 +140,5 @@ if [ "$keepfasl" != "yes" ]; then
   rm -f *.fasl
 fi
 
+echo "Good to go."
+exit 0
